- hosts: all
  become : false
  gather_facts: true
  any_errors_fatal: true

  vars:
    openio_zk_cluster_ip: "{{ groups['openio_zk_cluster'] | map('extract', hostvars, ['ansible_' + openio_iface, 'ipv4','address']) | list }}"
    openio_redis_cluster_ip: "{{ groups['openio_redis_cluster'] | map('extract', hostvars, ['ansible_' + openio_iface, 'ipv4','address']) | list }}"
    conscience_ip: "{{ groups['openio_conscience'] | map('extract', hostvars, ['ansible_' + openio_iface, 'ipv4','address']) | list | first }}"
    openio_network_private_ipaddress: "{{ hostvars[inventory_hostname]['ansible_' + openio_iface].ipv4.address }}"

  roles:
    - role: ansible-role-openio-sds
